name = "donglema-push-worker"
main = "src/index.js"
compatibility_date = "2026-06-12"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "SUBSCRIPTIONS"
id = "8d233c43a2eb4b79a4f41e3e59817fa3"
